version: '3'
   
services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
   
  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/chatbot'
    environment:
      - LANG=C.UTF-8
      - DB_PASSWORD=postgres
      - YANDEX_API_KEY
      - YANDEX_API_URL
   
volumes:
  postgres: